### ISSUE TITLE
global name 'transform_selection_regions' is not defined

### ISSUE THREAD

**Issue by nicosantangelo** [linktohack/VintageYankStack#1]
Hello!

I'm trying to use the package on MacOS (Yosemite) in Sublime Text 3 (Build 3038) and I'm getting an error when I yank  some text:

<img width="1302" alt="screen shot 2015-10-05 at 12 35 20 am" src="https://cloud.githubusercontent.com/assets/692077/10272627/245e553c-6af9-11e5-94ea-9eba3d6fe549.png">

I've reinstalled the package with no luck, it works fine with change and delete.

Thanks!

**Comment by linktohack** [comment]
Hi @NicoSantangelo,

Thanks for the report. The issue should be fixed by last commit. Please wait for moment for `Package Control' to update.

**Comment by nicosantangelo** [comment]
Perfect!

Thanks a lot for the quick fix, awesome package!

**Comment by linktohack** [comment]
Thanks again for the compliment! I'm closing this.
