### ISSUE TITLE
`Vintageous` compatability?

### ISSUE THREAD

**Issue by bangedorrunt** [linktohack/VintageYankStack#2]
Hi,

I'm using `Vintageous` plugin for _Vim_ keybinding. I tried to remap `VintageYankStack` to the following key but the new binding is not activated:

``` json
  {
    "keys": ["super+shift+alt+ctrl+r", "p"],
    "command": "vi_yank_stack",
    "args": {
      "forward": true
    },
    "context": [{
      "key": "vi_has_just_pasted"
    }]
  }
```

or 

``` json
  {
    "keys": ["super+shift+alt+ctrl+r", "p"],
    "command": "vi_yank_stack",
    "args": {
      "forward": true
    },
    "context": [{
      "key": "vi_has_just_pasted"
    }, {
      "key": "vi_command_mode_aware"
    }]
  }
```

I'm using _SublimeText build 3095_ on _OSX 10.11.2_

**Comment by linktohack** [comment]
Hi @babygau, `VintageYankStack` is not compatible with `Vintageous` atm as the two plugins are very different in architecture.

**Comment by bangedorrunt** [comment]
@linktohack thank you for your response. It would be great if you have plan to support `Vintageous` plugin. IMO, `Vintageous` are far superior to built-in `Vintage` plugin. 

Please feel free to close this issue if you don't have plan to support it, no pressure my friend!

**Comment by linktohack** [comment]
Actually I had a look on `Vintageous` and I think it's feasible to implement. The idea is to implement `shift_up` and `shift_down` methods to `Registers` class [1](https://github.com/guillermooo/Vintageous/blob/master/vi/registers.py#L40), which basically the same as the `set_register` in Vintage [2](https://github.com/linktohack/VintageYankStack/blob/master/vi_yank_stack.py#L10). The `EventListener` should return true for `_vi_p` and `_vi_big_p` instead.

Do you want to give it a try?

**Comment by bangedorrunt** [comment]
I wish I could but I don't know `Python`, I'm a web developer unfortunately @linktohack

**Comment by linktohack** [comment]
Ok, I'm closing this for now, if you want we to have a look later, feel free to reopen it.

**Comment by bangedorrunt** [comment]
Thank you @linktohack. Give me a week to learn a bit of Python and I'd like to work with you about this issue.
